name: Deploy Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/ktlint.yml"

jobs:   
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  ktlint:
     runs-on: ubuntu-latest
     steps:
       - name: "checkout"
         uses: actions/checkout@v2.3.2
       - name: "ktlint"
         uses: fabiocapasso93/gha-kotlin-linter@v1.0
